File.cwd!()
|> Path.join("day1.txt")
|> File.read!()
|> String.split(~r{\n\n})
|> Enum.map(fn elves ->
  elves
  |> String.split()
  |> Enum.map(&elem(Integer.parse(&1), 0))
  |> Enum.sum()
end)
|> Enum.sort()
|> Enum.reverse()
|> Enum.take(3)
|> Enum.sum()
|> IO.inspect()
